#ifndef MOTOR_AND_STEPPER_SETTINGS_H
#define MOTOR_AND_STEPPER_SETTINGS_H
#define MATRIX_SERIAL_BAUD_RATE 115200
#define SERIAL_READ_TIMEOUT_MS 20
#define MOTOR_PORT_FRONT_LEFT   1
#define MOTOR_PORT_FRONT_RIGHT  2
#define MOTOR_PORT_REAR_LEFT    3
#define MOTOR_PORT_REAR_RIGHT   4
#define MOTOR_DIRECTION_FRONT_LEFT   1
#define MOTOR_DIRECTION_FRONT_RIGHT  1
#define MOTOR_DIRECTION_REAR_LEFT    1
#define MOTOR_DIRECTION_REAR_RIGHT   1
#define TRAVEL_MOTOR_POWER_PERCENT 35
#define TURN_MOTOR_POWER_PERCENT   30
#define ENCODER_COUNTS_PER_WHEEL_TURN 0
#define WHEEL_DIAMETER_MM 0.0f
#define DISTANCE_BETWEEN_SCAN_AREAS_MM 0.0f
#define ENCODER_ARRIVAL_TOLERANCE_COUNTS 5
#define MOVE_TIMEOUT_MS 8000
#define SETTLE_AFTER_STOPPING_MS 400
#define STEPPER_STEP_PIN   0
#define STEPPER_DIR_PIN    0
#define STEPPER_ENABLE_PIN 0
#define STEPPER_ENABLE_IS_ACTIVE_LOW 1
#define STEPPER_FULL_STEPS_PER_TURN 200
#define STEPPER_MICROSTEPS 1
#define STEPPER_STEPS_PER_TURN (STEPPER_FULL_STEPS_PER_TURN * STEPPER_MICROSTEPS)
#define STEPPER_PULSE_WIDTH_US 5
#define STEPPER_STEP_INTERVAL_US 1200
#define STEPPER_MAXIMUM_STEPS_FROM_PARKED 0
#define COLOUR_SENSOR_PORT 1
#define COLOUR_SENSOR_READINGS_TO_AVERAGE 5
#define COLOUR_SENSOR_CHANNEL_COUNT 3
#endif  
