#ifndef XIAO_CAMERA_WIFI_AND_SERVER_SETTINGS_H
#define XIAO_CAMERA_WIFI_AND_SERVER_SETTINGS_H
#include "wifi_credentials.h"
#define CAMERA_NAME "ASIL_XIAO"
#define FIRMWARE_VERSION "1.0.0"
#define XIAO_UART_TX_PIN 43  
#define XIAO_UART_RX_PIN 44   
#define XIAO_UART_BAUD_RATE 115200
#define PHOTO_UPLOAD_PATH "/api/v1/scan_photo"
#define WIFI_CONNECT_TIMEOUT_MS 20000
#define WIFI_RETRY_DELAY_MS 3000
#define HTTP_TIMEOUT_MS 60000
#define UPLOAD_MAX_ATTEMPTS 3
#define UPLOAD_BACKOFF_START_MS 800
#define CAMERA_MODEL_XIAO_ESP32S3
#define CAMERA_JPEG_QUALITY 8
#define CAMERA_FRAME_BUFFERS 2
#define FRAMES_TO_DISCARD_AT_STARTUP 3
#endif  
